### ISSUE TITLE
io::CharsError not found

### ISSUE THREAD

**Issue by 0x8f701** [Munksgaard/inquirer-rs#16]
error[E0412]: cannot find type `CharsError` in module `io`
  --> src/error.rs:16:24
   |
16 |         Chars(err: io::CharsError) {
   |                        ^^^^^^^^^^ not found in `io`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0412`.
error: Could not compile `inquirer`.

To learn more, run the command again with --verbose.

**Comment by 0x8f701** [comment]
rustc 1.35.0-nightly (e4c66afba 2019-04-13)

**Comment by Munksgaard** [comment]
Thank you for reporting the issue @GopherJ, I'll take a look later today.
